'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ucInputVSSPID

    '''<summary>
    '''panVSSPIDDocumentaryProof control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panVSSPIDDocumentaryProof As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''trDocumentaryProof control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trDocumentaryProof As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblDocumentaryProofTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDocumentaryProofTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkDocumentaryProof control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDocumentaryProof As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ddlDocumentaryProof control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDocumentaryProof As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''imgDocumentaryProofError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgDocumentaryProofError As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''panPIDInstitutionCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panPIDInstitutionCode As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblPIDInstitutionCodeText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPIDInstitutionCodeText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPIDInstitutionCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPIDInstitutionCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgPIDInstitutionCodeError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgPIDInstitutionCodeError As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''btnSearchPID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearchPID As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lblPIDInstitutionCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPIDInstitutionCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPIDInstitutionNameText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPIDInstitutionNameText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPIDInstitutionName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPIDInstitutionName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPIDInstitutionNameChi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPIDInstitutionNameChi As Global.System.Web.UI.WebControls.Label
End Class
