'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization
Imports Microsoft.Web.Services3.Design

'
'This source code was auto-generated by wsdl, Version=4.0.30319.33440.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440"), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Web.Services.WebServiceBindingAttribute(Name:="PortBinding", [Namespace]:="http://eligibilityservice.ocsss.ecs/")> _
Partial Public Class OCSSSProxy
    Inherits Microsoft.Web.Services3.WebServicesClientProtocol
    'Inherits System.Web.Services.Protocols.SoapHttpClientProtocol

    Private isEligibleOperationCompleted As System.Threading.SendOrPostCallback

    Private _strHashedPassPhrase As String = String.Empty
    Public Property HashedPassPhrase() As String
        Get
            Return _strHashedPassPhrase
        End Get
        Set(value As String)
            _strHashedPassPhrase = value
        End Set
    End Property

    '''<remarks/>
    Public Sub New()
        MyBase.New()
        Me.Url = "https://localhost"
    End Sub

    '''<remarks/>
    Public Event isEligibleCompleted As isEligibleCompletedEventHandler

    '''<remarks/>
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://eligibilityservice.ocsss.ecs/", ResponseNamespace:="http://eligibilityservice.ocsss.ecs/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
    Public Function isEligible(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal arg0 As eligibilityRequest) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> eligibilityResponse

        ' Set the policy to secure the message and remove unnecessary headers
        Dim strAuthToken As String = HashedPassPhrase()

        Dim p As New Policy
        p.Assertions.Add(New CustomSecurityAssertion(strAuthToken))
        Me.SetPolicy(p)

        Dim results() As Object = Me.Invoke("isEligible", New Object() {arg0})
        Return CType(results(0), eligibilityResponse)
    End Function

    '''<remarks/>
    Public Function BeginisEligible(ByVal arg0 As eligibilityRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("isEligible", New Object() {arg0}, callback, asyncState)
    End Function

    '''<remarks/>
    Public Function EndisEligible(ByVal asyncResult As System.IAsyncResult) As eligibilityResponse
        Dim results() As Object = Me.EndInvoke(asyncResult)
        Return CType(results(0), eligibilityResponse)
    End Function

    '''<remarks/>
    Public Overloads Sub isEligibleAsync(ByVal arg0 As eligibilityRequest)
        Me.isEligibleAsync(arg0, Nothing)
    End Sub

    '''<remarks/>
    Public Overloads Sub isEligibleAsync(ByVal arg0 As eligibilityRequest, ByVal userState As Object)
        If (Me.isEligibleOperationCompleted Is Nothing) Then
            Me.isEligibleOperationCompleted = AddressOf Me.OnisEligibleOperationCompleted
        End If
        Me.InvokeAsync("isEligible", New Object() {arg0}, Me.isEligibleOperationCompleted, userState)
    End Sub

    Private Sub OnisEligibleOperationCompleted(ByVal arg As Object)
        If (Not (Me.isEligibleCompletedEvent) Is Nothing) Then
            Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
            RaiseEvent isEligibleCompleted(Me, New isEligibleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
        End If
    End Sub

    '''<remarks/>
    Public Shadows Sub CancelAsync(ByVal userState As Object)
        MyBase.CancelAsync(userState)
    End Sub

    ''' <summary>
    ''' Add custom header to HTTP Request
    ''' </summary>
    ''' <param name="uri"></param>
    ''' <returns></returns>
    ''' <remarks></remarks>
    Protected Overrides Function GetWebRequest(uri As Uri) As Net.WebRequest
        ' Get HTTP Request
        Dim request As Net.WebRequest = MyBase.GetWebRequest(uri)
        ' Add custom HTTP Header "USER_ID: hahvcs" for calling DH OCSSS
        request.Headers.Add("USER_ID", "hahcvs")
        Return request
    End Function
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://eligibilityservice.ocsss.ecs/")>  _
Partial Public Class eligibilityRequest
    
    'Private messageIdField As String
    
    Private patientIdField As String

    ' ====================================================
    ' Remove obsolete input parameter in OCSSS web service
    ' ====================================================
    ' '''<remarks/>
    '<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    'Public Property messageId() As String
    '    Get
    '        Return Me.messageIdField
    '    End Get
    '    Set
    '        Me.messageIdField = value
    '    End Set
    'End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property patientId() As String
        Get
            Return Me.patientIdField
        End Get
        Set
            Me.patientIdField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://eligibilityservice.ocsss.ecs/")>  _
Partial Public Class eligibilityResponse
    
    Private checkingResultField As String
    
    Private errorMessageField As String
    
    Private messageIdField As String
    
    Private replyDateTimeField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property checkingResult() As String
        Get
            Return Me.checkingResultField
        End Get
        Set
            Me.checkingResultField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property errorMessage() As String
        Get
            Return Me.errorMessageField
        End Get
        Set
            Me.errorMessageField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property messageId() As String
        Get
            Return Me.messageIdField
        End Get
        Set
            Me.messageIdField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property replyDateTime() As String
        Get
            Return Me.replyDateTimeField
        End Get
        Set
            Me.replyDateTimeField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")>  _
Public Delegate Sub isEligibleCompletedEventHandler(ByVal sender As Object, ByVal e As isEligibleCompletedEventArgs)

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code")>  _
Partial Public Class isEligibleCompletedEventArgs
    Inherits System.ComponentModel.AsyncCompletedEventArgs
    
    Private results() As Object
    
    Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
        MyBase.New(exception, cancelled, userState)
        Me.results = results
    End Sub
    
    '''<remarks/>
    Public ReadOnly Property Result() As eligibilityResponse
        Get
            Me.RaiseExceptionIfNecessary
            Return CType(Me.results(0),eligibilityResponse)
        End Get
    End Property
End Class
