'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ConversionRateManagement

    '''<summary>
    '''tsmConversionRateManagement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tsmConversionRateManagement As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''imgHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgHeader As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''upanConversionRateManagement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upanConversionRateManagement As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''udcInfoMessageBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents udcInfoMessageBox As Global.CustomControls.InfoMessageBox

    '''<summary>
    '''udcMessageBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents udcMessageBox As Global.CustomControls.MessageBox

    '''<summary>
    '''mvConversionRateManagement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvConversionRateManagement As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''vNotice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vNotice As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''tblNotice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblNotice As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''lblCurrentConversionRateInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrentConversionRateInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mvCurrentConversionRateInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvCurrentConversionRateInfo As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''vNoCurrentConversionRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vNoCurrentConversionRate As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''tblNoCurrentConversionRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblNoCurrentConversionRate As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''lblCurrentConversionRateRecord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrentConversionRateRecord As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''vCurrentConversionRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vCurrentConversionRate As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''tblCurrentConversionRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblCurrentConversionRate As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''tblCurrentConversionRateDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblCurrentConversionRateDetail As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''lblCurrentConversionRateIDText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrentConversionRateIDText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCurrentConversionRateID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrentConversionRateID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCurrentEffectiveDateText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrentEffectiveDateText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCurrentEffectiveDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrentEffectiveDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCurrentConversionRateText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrentConversionRateText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCurrentConversionRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrentConversionRate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCurrentConversionRateCreateByText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrentConversionRateCreateByText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCurrentConversionRateCreateBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrentConversionRateCreateBy As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCurrentConversionRateCreateDtm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrentConversionRateCreateDtm As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCurrentConversionRateApprovedByText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrentConversionRateApprovedByText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCurrentConversionRateApprovedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrentConversionRateApprovedBy As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCurrentConversionRateApprovedDtm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrentConversionRateApprovedDtm As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNextConversionRateInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNextConversionRateInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mvNextConversionRateInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvNextConversionRateInfo As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''vNoNextConversionRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vNoNextConversionRate As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''tblNoNextConversionRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblNoNextConversionRate As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''lblNextConversionRateRecord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNextConversionRateRecord As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''vNextConversionRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vNextConversionRate As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''tblNextConversionRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblNextConversionRate As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''tblNextConversionRateDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblNextConversionRateDetail As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''lblNextConversionRateIDText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNextConversionRateIDText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNextConversionRateID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNextConversionRateID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDeleteApprovedConversionRateAsterisk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDeleteApprovedConversionRateAsterisk As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNextEffectiveDateText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNextEffectiveDateText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNextEffectiveDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNextEffectiveDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNextConversionRateText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNextConversionRateText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNextConversionRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNextConversionRate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNextConversionRateCreateByText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNextConversionRateCreateByText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNextConversionRateCreateBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNextConversionRateCreateBy As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNextConversionRateCreateDtm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNextConversionRateCreateDtm As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNextConversionRateApprovedByText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNextConversionRateApprovedByText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNextConversionRateApprovedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNextConversionRateApprovedBy As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNextConversionRateApprovedDtm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNextConversionRateApprovedDtm As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trNextConversionRateRemark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trNextConversionRateRemark As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''lblNextConversionRateRemarkAsterisk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNextConversionRateRemarkAsterisk As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNextConversionRateRemark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNextConversionRateRemark As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trDeleteApprovedRecord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trDeleteApprovedRecord As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''ibtnDeleteApprovedRecord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnDeleteApprovedRecord As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lblPendingConversionRateRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPendingConversionRateRequest As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mvPendingConversionRateRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvPendingConversionRateRequest As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''vNoPendingConversionRateRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vNoPendingConversionRateRequest As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''tblNoPendingConversionRateRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblNoPendingConversionRateRequest As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''lblPendingConversionRateRequestRecord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPendingConversionRateRequestRecord As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ibtnCreateConversionRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnCreateConversionRate As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''vCreateConversionRateRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vCreateConversionRateRequest As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''tblCreateConversionRateRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblCreateConversionRateRequest As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''tblCreateConversionRateDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblCreateConversionRateDetail As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''lblCreateEffectiveDateText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCreateEffectiveDateText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtEffectiveDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEffectiveDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''filterEffectiveDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filterEffectiveDate As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''ibtnEffectiveDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnEffectiveDate As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''imgEffectiveDateAlert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgEffectiveDateAlert As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''calEffectiveDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calEffectiveDate As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''lblCreateConversionRateText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCreateConversionRateText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCreateConversionRateFormulaText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCreateConversionRateFormulaText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtConversionRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConversionRate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''filterConversionRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filterConversionRate As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''imgConversionRateAlert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgConversionRateAlert As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblCreateRequestTypeText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCreateRequestTypeText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCreateRequestType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCreateRequestType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ibtnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnSave As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibtnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnCancel As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''vConfirmConversionRateRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vConfirmConversionRateRequest As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''tblConfirmConversionRateRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblConfirmConversionRateRequest As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''tblConfirmConversionRateDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblConfirmConversionRateDetail As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''lblConfirmEffectiveDateText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConfirmEffectiveDateText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblConfirmEffectiveDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConfirmEffectiveDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblConfirmConversionRateText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConfirmConversionRateText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblConfirmConversionRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConfirmConversionRate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblConfirmRequestTypeText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConfirmRequestTypeText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblConfirmRequestType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConfirmRequestType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trConfirmCreation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trConfirmCreation As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''ibtnConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnConfirm As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibtnBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnBack As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''trCancelBackToHome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trCancelBackToHome As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''ibtnCancelBackToHome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnCancelBackToHome As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''vPendingApprovalConversionRateRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vPendingApprovalConversionRateRequest As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''tblPendingApprovalConversionRateRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblPendingApprovalConversionRateRequest As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''tblPendingApprovalConversionRateDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblPendingApprovalConversionRateDetail As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''lblPendingApprovalEffectiveDateText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPendingApprovalEffectiveDateText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPendingApprovalEffectiveDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPendingApprovalEffectiveDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPendingApprovalConversionRateText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPendingApprovalConversionRateText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPendingApprovalConversionRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPendingApprovalConversionRate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPendingApprovalRequestTypeText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPendingApprovalRequestTypeText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPendingApprovalRequestType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPendingApprovalRequestType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPendingApprovalCreatedByText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPendingApprovalCreatedByText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPendingApprovalCreatedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPendingApprovalCreatedBy As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPendingApprovalCreatedDtm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPendingApprovalCreatedDtm As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ibtnDeletePendingRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnDeletePendingRequest As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''vPendingDeleteApprovedConversionRateRecord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vPendingDeleteApprovedConversionRateRecord As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''tblPendingDeleteApprovedConversionRateRecord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblPendingDeleteApprovedConversionRateRecord As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''vPendingDeleteApprovedConversionRateDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vPendingDeleteApprovedConversionRateDetail As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''lblPendingDeleteApprovedConversionRateIDText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPendingDeleteApprovedConversionRateIDText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPendingDeleteApprovedConversionRateID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPendingDeleteApprovedConversionRateID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPendingDeleteApprovedEffectiveDateText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPendingDeleteApprovedEffectiveDateText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPendingDeleteApprovedEffectiveDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPendingDeleteApprovedEffectiveDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPendingDeleteApprovedConversionRateText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPendingDeleteApprovedConversionRateText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPendingDeleteApprovedConversionRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPendingDeleteApprovedConversionRate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPendingDeleteApprovedRequestTypeText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPendingDeleteApprovedRequestTypeText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPendingDeleteApprovedRequestType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPendingDeleteApprovedRequestType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPendingDeleteApprovedCreatedByText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPendingDeleteApprovedCreatedByText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPendingDeleteApprovedCreatedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPendingDeleteApprovedCreatedBy As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPendingDeleteApprovedCreatedDtm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPendingDeleteApprovedCreatedDtm As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPendingDeleteApprovedByText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPendingDeleteApprovedByText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPendingDeleteApprovedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPendingDeleteApprovedBy As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPendingDeleteApprovedDtm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPendingDeleteApprovedDtm As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPendingDeleteApprovedRequestedByText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPendingDeleteApprovedRequestedByText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPendingDeleteApprovedRequestedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPendingDeleteApprovedRequestedBy As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPendingDeleteApprovedRequestedDtm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPendingDeleteApprovedRequestedDtm As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ibtnReturn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnReturn As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''panConfirmMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panConfirmMsg As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''panConfirmMsgHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panConfirmMsgHeading As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblMsgTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsgTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgMsg As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ibtnDialogConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnDialogConfirm As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibtnDialogCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnDialogCancel As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnHiddenDeletePendingRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHiddenDeletePendingRequest As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ModalPopupExtenderConfirmDeletePendingRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModalPopupExtenderConfirmDeletePendingRequest As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''btnHiddenDeleteApprovedRecord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHiddenDeleteApprovedRecord As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ModalPopupExtenderConfirmDeleteApprovedRecord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModalPopupExtenderConfirmDeleteApprovedRecord As Global.AjaxControlToolkit.ModalPopupExtender
End Class
