'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MyProfileV2

    '''<summary>
    '''imgHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgHeader As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtTabIndex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTabIndex As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''udcInfoMsgBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents udcInfoMsgBox As Global.CustomControls.InfoMessageBox

    '''<summary>
    '''udcErrMsgBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents udcErrMsgBox As Global.CustomControls.MessageBox

    '''<summary>
    '''mvMyProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvMyProfile As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''vServiceProvider control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vServiceProvider As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''TabContainer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabContainer1 As Global.AjaxControlToolkit.TabContainer

    '''<summary>
    '''tabPersonalParticulars control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabPersonalParticulars As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''lblSPNameText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSPNameText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSPEname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSPEname As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSPCname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSPCname As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSPHKIDText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSPHKIDText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSPHKID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSPHKID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSPAddressText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSPAddressText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSPAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSPAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSPEmailText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSPEmailText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSPEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSPEmail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSPContactNoText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSPContactNoText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSPContactNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSPContactNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSPFaxText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSPFaxText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSPFax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSPFax As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSPEnrolledSchemeText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSPEnrolledSchemeText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gvSPEnrolledScheme control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvSPEnrolledScheme As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''tabMOInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabMOInfo As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''chkMOShowActiveOnly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMOShowActiveOnly As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''gvMOInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvMOInfo As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''tabPracticeInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabPracticeInfo As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''chkShowActive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowActive As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''gvPracticeInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvPracticeInfo As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''tabBankInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabBankInfo As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''chkBankAcctShowActiveOnly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkBankAcctShowActiveOnly As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''gvBankInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvBankInfo As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''tabSystemInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabSystemInfo As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''lblSPLoginInformation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSPLoginInformation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSPIDText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSPIDText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSPID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSPID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUsernameText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUsernameText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUsername control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUsername As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtUsername control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUsername As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgUsernameError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgUsernameError As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''btnChkAvail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnChkAvail As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''trGetUsernameFromEHRSS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trGetUsernameFromEHRSS As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''btnGetUsernameFromEHRSS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGetUsernameFromEHRSS As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''tdUsernameTips control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdUsernameTips As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''lblSPUsernameTip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSPUsernameTip As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSPUsernameTip1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSPUsernameTip1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSPUsernameTip2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSPUsernameTip2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSPUsernameTip2a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSPUsernameTip2a As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSPUsernameTip2b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSPUsernameTip2b As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSPUsernameTip2c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSPUsernameTip2c As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTokenSerialNoText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTokenSerialNoText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTokenSerialNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTokenSerialNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PanelSPSystemSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelSPSystemSettings As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblSPSystemSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSPSystemSettings As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PanelSPDefaultLang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelSPDefaultLang As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblDefaultLangText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDefaultLangText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlDefaultLang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDefaultLang As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''PanelPrintingOptionSetting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelPrintingOptionSetting As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblDefaultPrintOptionText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDefaultPrintOptionText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSelectPrintOptionText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectPrintOptionText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgSPSelectPrintOptionError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgSPSelectPrintOptionError As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''tblPrintOption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblPrintOption As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''trNotToPrint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trNotToPrint As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rbNotPrint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbNotPrint As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtNotPrintRemind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNotPrintRemind As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trPrintFullVersion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trPrintFullVersion As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rbPrintFull control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbPrintFull As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''trPrintCondensed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trPrintCondensed As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rbPrintCondensed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbPrintCondensed As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtPrintCondensedRemind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPrintCondensedRemind As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSPPasswordSetting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSPPasswordSetting As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PanelWebPasswordSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelWebPasswordSettings As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkChgWebPWD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkChgWebPWD As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''tdPwdCell01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdPwdCell01 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''tdPwdCell02 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdPwdCell02 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''PanelWebPasswordTips control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelWebPasswordTips As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblWebPwdTipsText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWebPwdTipsText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblWebPwdTips1Text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWebPwdTips1Text As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblWebPwdTips1aText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWebPwdTips1aText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblWebPwdTips1bText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWebPwdTips1bText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblWebPwdTips1cText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWebPwdTips1cText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblWebPwdTips1dText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWebPwdTips1dText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblWebPwdTips2Text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWebPwdTips2Text As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblWebPwdTips3Text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWebPwdTips3Text As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PanelWebPassword01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelWebPassword01 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblOldWebPwdText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOldWebPwdText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNewWebPwdText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNewWebPwdText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblConfirmNewWebPwdText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConfirmNewWebPwdText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tdPwdCell03 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdPwdCell03 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''PanelWebPassword02 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelWebPassword02 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtOldWebPwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOldWebPwd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgSPOldPWDError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgSPOldPWDError As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''txtNewWebPwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewWebPwd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgSPNewPWDError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgSPNewPWDError As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''txtConfirmNewWebPwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConfirmNewWebPwd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgSPConfirmNewPWDError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgSPConfirmNewPWDError As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''PanelIVRSPasswordSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelIVRSPasswordSettings As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkChgIVRSPwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkChgIVRSPwd As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkActivateIVRSPwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkActivateIVRSPwd As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''tdIVRSPwdCell01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdIVRSPwdCell01 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''PanelIVRSPassword01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelIVRSPassword01 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblIVRSOldPwdText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIVRSOldPwdText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblIVRSNewPwdText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIVRSNewPwdText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblConfirmNewIVRSPwdText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConfirmNewIVRSPwdText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tdIVRSPwdCell02 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdIVRSPwdCell02 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''PanelIVRSPassword02 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelIVRSPassword02 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtIVRSOldPwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIVRSOldPwd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgSPOldIVRSPWDError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgSPOldIVRSPWDError As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''txtIVRSNewPwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIVRSNewPwd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgSPNewIVRSPWDError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgSPNewIVRSPWDError As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''txtConfirmNewIVRSPwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConfirmNewIVRSPwd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgSPConfirmNewIVRSPWDError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgSPConfirmNewIVRSPWDError As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''tdIVRSPwdCell03 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdIVRSPwdCell03 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''PanelIVRSPasswordTips control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelIVRSPasswordTips As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblIVRSPwdTipsText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIVRSPwdTipsText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblIVRSPwdTips1Text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIVRSPwdTips1Text As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblIVRSPwdTips2Text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIVRSPwdTips2Text As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblIVRSPwdTips3Text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIVRSPwdTips3Text As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEdit As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''FilteredUserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FilteredUserName As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''FilteredNewWebPwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FilteredNewWebPwd As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''FilteredConfirmNewWebPwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FilteredConfirmNewWebPwd As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''FilteredIVRSOldPwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FilteredIVRSOldPwd As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''FilteredIVRSNewPwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FilteredIVRSNewPwd As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''FilteredConfirmNewIVRSPwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FilteredConfirmNewIVRSPwd As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''tabDataEntryInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabDataEntryInfo As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''lblDEListText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDEListText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbDEFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDEFilter As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''txtDEFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDEFilter As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hfDEFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfDEFilter As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''imgDEFilterError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgDEFilterError As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''btnFilterDEAcct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFilterDEAcct As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnClearDEAcctSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClearDEAcctSearch As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''TextBoxWatermarkExtender1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxWatermarkExtender1 As Global.AjaxControlToolkit.TextBoxWatermarkExtender

    '''<summary>
    '''trUsername control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trUsername As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblUsernameHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUsernameHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trUsernameFound control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trUsernameFound As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblUsernameFound control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUsernameFound As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trUsernameNotFound control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trUsernameNotFound As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblUsernameNotFound control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUsernameNotFound As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gvdataEntryAcc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvdataEntryAcc As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblDEAcctInfoText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDEAcctInfoText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDELoginInformation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDELoginInformation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDELoginIDText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDELoginIDText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDELoginID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDELoginID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDEloginID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDEloginID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgDELoginIDError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgDELoginIDError As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''tdDEUsernameTip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdDEUsernameTip As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''lblDEUsernameTip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDEUsernameTip As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDEUsernameTip1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDEUsernameTip1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDEUsernameTip2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDEUsernameTip2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDEUsernameTip2a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDEUsernameTip2a As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDEUsernameTip2b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDEUsernameTip2b As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDEUsernameTip2c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDEUsernameTip2c As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPracticeText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPracticeText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnDESelectAllPractice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDESelectAllPractice As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnDEUnselectAllPractice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDEUnselectAllPractice As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''chkPracticeList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPracticeList As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''lblDENoPractice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDENoPractice As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgDEPracticeError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgDEPracticeError As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblDEPasswordSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDEPasswordSettings As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PanelDEWebPasswordSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelDEWebPasswordSettings As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkChgDEPWD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkChgDEPWD As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''PanelDEWebPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelDEWebPassword As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblDENewPWDText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDENewPWDText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDENewPWD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDENewPWD As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgDENewPWDError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgDENewPWDError As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblDEConfirmNewPWDText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDEConfirmNewPWDText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDEConfirmNewPWD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDEConfirmNewPWD As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgDEConfirmNewPWDError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgDEConfirmNewPWDError As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblDEWebPwdTipsText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDEWebPwdTipsText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDEWebPwdTips1Text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDEWebPwdTips1Text As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDEWebPwdTips1aText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDEWebPwdTips1aText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDEWebPwdTips1bText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDEWebPwdTips1bText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDEWebPwdTips1cText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDEWebPwdTips1cText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDEWebPwdTips1dText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDEWebPwdTips1dText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDEWebPwdTips2Text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDEWebPwdTips2Text As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDEWebPwdTips3Text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDEWebPwdTips3Text As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDEAccountStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDEAccountStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDEAcctStatusText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDEAcctStatusText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkDESuspend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDESuspend As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblDEAcctLockedText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDEAcctLockedText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkDEAccountLocked control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDEAccountLocked As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnCancelDEAcct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelDEAcct As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnAddDEAcct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddDEAcct As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnEditDEAcct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditDEAcct As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnSaveDEAcct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveDEAcct As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''FilteredDEloginID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FilteredDEloginID As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''FilteredDENewPWD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FilteredDENewPWD As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''FilteredDEConfirmNewPWD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FilteredDEConfirmNewPWD As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''ibtnJoinPCD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnJoinPCD As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''vDataEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vDataEntry As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''panDataEntryChgPwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panDataEntryChgPwd As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblDEChangeLoginInformation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDEChangeLoginInformation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDEUsernameText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDEUsernameText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDEUsername control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDEUsername As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PanelDataEntryPrintingOptionSetting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelDataEntryPrintingOptionSetting As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblDEChangeSystemSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDEChangeSystemSettings As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDEChangeDefaultPrintOption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDEChangeDefaultPrintOption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDEChangeSelectPrintOptionText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDEChangeSelectPrintOptionText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgDESelectPrintOptionError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgDESelectPrintOptionError As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''tblDEPrintOption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblDEPrintOption As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''trDENotToPrint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trDENotToPrint As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rbDEChangeNotPrint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbDEChangeNotPrint As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtDEChangeNotPrintRemind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDEChangeNotPrintRemind As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trDEPrintFullVersion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trDEPrintFullVersion As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rbDEChangePrintFull control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbDEChangePrintFull As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''trDEPrintCondensed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trDEPrintCondensed As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rbDEChangePrintCondensed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbDEChangePrintCondensed As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtDEChangePrintCondensedRemind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDEChangePrintCondensedRemind As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDEChangePasswordSetting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDEChangePasswordSetting As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PanelDEChangeWebPasswordSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelDEChangeWebPasswordSettings As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkDEChangePassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDEChangePassword As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''tdDEChgPwdCell01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdDEChgPwdCell01 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''tdDEChgPwdCell03 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdDEChgPwdCell03 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''PanelDEChangeWebPasswordTips control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelDEChangeWebPasswordTips As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblDEWebPWDTips control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDEWebPWDTips As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDEWebPWDTips1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDEWebPWDTips1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDEWebPWDTips1a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDEWebPWDTips1a As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDEWebPWDTips1b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDEWebPWDTips1b As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDEWebPWDTips1c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDEWebPWDTips1c As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDEWebPWDTips1d control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDEWebPWDTips1d As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDEWebPWDTips2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDEWebPWDTips2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDEWebPWDTips3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDEWebPWDTips3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PanelDEChangeWebPassword01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelDEChangeWebPassword01 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblDEOLDPasswordText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDEOLDPasswordText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDENEWPasswordText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDENEWPasswordText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDEConfirmNEWPasswordText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDEConfirmNEWPasswordText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tdDEChgPwdCell02 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdDEChgPwdCell02 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''PanelDEChangeWebPassword02 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelDEChangeWebPassword02 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtDEOLDPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDEOLDPassword As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgDEOLDPasswordError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgDEOLDPasswordError As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''txtDENEWPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDENEWPassword As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgDENEWPasswordError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgDENEWPasswordError As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''txtDEConfirmNEWPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDEConfirmNEWPassword As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgDEConfirmNEWPasswordError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgDEConfirmNEWPasswordError As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''btnDECancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDECancel As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnDEEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDEEdit As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnDESave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDESave As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''FilteredDENEWPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FilteredDENEWPassword As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''FilteredDEConfirmNEWPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FilteredDEConfirmNEWPassword As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''btnDataEntryChgPWDReturn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDataEntryChgPWDReturn As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''panSchemeNameHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panSchemeNameHelp As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''panSchemeNameHelpHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panSchemeNameHelpHeading As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblSchemeNameHelpHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSchemeNameHelpHeading As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''panSchemeNameHelpContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panSchemeNameHelpContent As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''udcSchemeLegend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents udcSchemeLegend As Global.HCSP.SchemeLegend

    '''<summary>
    '''ibtnCloseSchemeNameHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnCloseSchemeNameHelp As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnHiddenSchemeNameHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHiddenSchemeNameHelp As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''popupSchemeNameHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupSchemeNameHelp As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''panTokenPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panTokenPopup As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ucInputTokenPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucInputTokenPopup As Global.HCSP.ucInputTokenPopup

    '''<summary>
    '''btnTokenPopupDummy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTokenPopupDummy As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ModalPopupExtenderToken control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModalPopupExtenderToken As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''panTypeOfPracticePopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panTypeOfPracticePopup As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ucTypeOfPracticePopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucTypeOfPracticePopup As Global.HCSP.ucTypeOfPracticePopup

    '''<summary>
    '''btnTypeOfPracticePopupDummy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTypeOfPracticePopupDummy As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ModalPopupExtenderTypeOfPractice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModalPopupExtenderTypeOfPractice As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''panPCDEnrolledPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panPCDEnrolledPopup As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ucPCDEnrolledPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucPCDEnrolledPopup As Global.HCSP.ucPCDEnrolledPopup

    '''<summary>
    '''btnPCDEnrolledPopupDummy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPCDEnrolledPopupDummy As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ModalPopupExtenderPCDEnrolled control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModalPopupExtenderPCDEnrolled As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''panNoticePopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panNoticePopup As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ucNoticePopUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucNoticePopUp As Global.HCSP.ucNoticePopUp

    '''<summary>
    '''btnNoticePopupDummy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNoticePopupDummy As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ModalPopupExtenderNotice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModalPopupExtenderNotice As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''panReturnCodeHandlingPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panReturnCodeHandlingPopup As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ucReturnCodeHandlingPopUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucReturnCodeHandlingPopUp As Global.HCSP.ucNoticePopUp

    '''<summary>
    '''btnReturnCodeHandlingPopUpDummy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReturnCodeHandlingPopUpDummy As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ModalPopupExtenderReturnCodeHandling control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModalPopupExtenderReturnCodeHandling As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''panNoticeLogoutEHSPopUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panNoticeLogoutEHSPopUp As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ucNoticeLogoutEHSPopUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucNoticeLogoutEHSPopUp As Global.HCSP.ucNoticePopUp

    '''<summary>
    '''btnNoticeLogoutEHSPopupDummy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNoticeLogoutEHSPopupDummy As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ModalPopupExtenderNoticeLogoutEHS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModalPopupExtenderNoticeLogoutEHS As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''panGetUsernameFromeHRSS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panGetUsernameFromeHRSS As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''panGetUsernameFromeHRSSHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panGetUsernameFromeHRSSHeading As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblMsgTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsgTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgMsg As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''chkGetUsernameFromEHRSS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkGetUsernameFromEHRSS As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ibtnConsentCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnConsentCancel As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibtnConsentConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnConsentConfirm As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibtnConsentConfirmDisable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnConsentConfirmDisable As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnGetUsernameFromEHRSSDummy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGetUsernameFromEHRSSDummy As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ModalPopupExtenderConfirmConsent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModalPopupExtenderConfirmConsent As Global.AjaxControlToolkit.ModalPopupExtender
End Class
