'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ucInputCOVID19

    '''<summary>
    '''panCOVID19Category control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panCOVID19Category As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblCategoryText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategoryText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rbCategorySelection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbCategorySelection As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''imgCategoryError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCategoryError As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''panCOVID19Detail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panCOVID19Detail As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''panCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panCategory As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblCCategoryText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCCategoryText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlCCategoryCovid19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCCategoryCovid19 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''imgCCategoryError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCCategoryError As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblCVaccineBrandText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCVaccineBrandText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlCVaccineBrandCovid19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCVaccineBrandCovid19 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCVaccineBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCVaccineBrand As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgCVaccineBrandError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCVaccineBrandError As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblCVaccineLotNoText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCVaccineLotNoText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlCVaccineLotNoCovid19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCVaccineLotNoCovid19 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCVaccineLotNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCVaccineLotNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgCVaccineLotNoError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCVaccineLotNoError As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''panDose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panDose As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblCDoseText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCDoseText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlCDoseCovid19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCDoseCovid19 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''imgCDoseError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCDoseError As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''trCContactNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trCContactNo As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblCContactNoText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCContactNoText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCContactNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCContactNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgCContactNoError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCContactNoError As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''fteCContactNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fteCContactNo As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''lblCRemarkText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCRemarkText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCRemark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCRemark As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgCRemarkError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCRemarkError As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''fteCRemark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fteCRemark As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''trJoinEHRSS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trJoinEHRSS As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblCJoinEHRSSText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCJoinEHRSSText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkCJoinEHRSS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCJoinEHRSS As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''udcClaimVaccineInputCOVID19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents udcClaimVaccineInputCOVID19 As Global.HCVU.ClaimVaccineInput
End Class
