'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3082
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace UIControl.DocTypeText

    '''<summary>
    '''ucReadOnlyID235B class.
    '''</summary>
    '''<remarks>
    '''Auto-generated class.
    '''</remarks>
    Partial Public Class ucReadOnlyID235B

        '''<summary>
        '''panReadonlyVerticalID235B control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panReadonlyVerticalID235B As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''panReadonlyTempAccountRefNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panReadonlyTempAccountRefNo As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblReadonlyRefenceText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReadonlyRefenceText As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblReadonlyReferenceNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReadonlyReferenceNo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''panReadonlyTempAccountNotice control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panReadonlyTempAccountNotice As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblReadonlyOpen control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReadonlyOpen As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblReadonlyConfirmTempAcctText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReadonlyConfirmTempAcctText As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblReadonlyClose control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReadonlyClose As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''panReadonlyCreationDatetime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panReadonlyCreationDatetime As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblReadonlyCreationDateTimeText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReadonlyCreationDateTimeText As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblReadonlyCreationDateTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReadonlyCreationDateTime As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''tblID235B control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblID235B As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblReadonlyDocumentTypeText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReadonlyDocumentTypeText As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblReadonlyDocumentType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReadonlyDocumentType As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblReadonlyBENoText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReadonlyBENoText As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblReadonlyBENo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReadonlyBENo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblReadonlyNameText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReadonlyNameText As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblReadonlyEName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReadonlyEName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblReadonlyGenderText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReadonlyGenderText As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblReadonlyGender control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReadonlyGender As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblReadonlyDOBText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReadonlyDOBText As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblReadonlyDOB control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReadonlyDOB As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblReadonlyPmtRemainText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReadonlyPmtRemainText As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblReadonlyPmtRemain control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReadonlyPmtRemain As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
