'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PrivateClinicalVaccineLotApproval

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''imgHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgHeader As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''udcInfoBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents udcInfoBox As Global.CustomControls.InfoMessageBox

    '''<summary>
    '''msgBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents msgBox As Global.CustomControls.MessageBox

    '''<summary>
    '''pnlEnquiry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEnquiry As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''MultiViewEnquiry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MultiViewEnquiry As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''ViewSearchCriteria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewSearchCriteria As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''lblVaccScheme control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVaccScheme As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlVaccScheme control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlVaccScheme As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''imgVaccCentreAlert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgVaccCentreAlert As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''ibtnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnSearch As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ViewSearchResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewSearchResult As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''btnHidden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHidden As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''udcCollapsibleSearchCriteriaReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents udcCollapsibleSearchCriteriaReview As Global.HCVU.ucCollapsibleSearchCriteriaReview

    '''<summary>
    '''pnlSearchCriteriaReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSearchCriteriaReview As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblResultVaccineSchemeText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblResultVaccineSchemeText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblResultSchemeVaccNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblResultSchemeVaccNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gvResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvResult As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''ibtnSearchResultBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnSearchResultBack As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ViewDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewDetails As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''lblVaccineLotTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVaccineLotTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDetailTitleRequestID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDetailTitleRequestID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDetailRequestID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDetailRequestID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDetailTitleScheme control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDetailTitleScheme As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDetailScheme control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDetailScheme As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trBrandName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trBrandName As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblDetailTitleBrandName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDetailTitleBrandName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDetailBrandName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDetailBrandName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDetailTitleBrandTradeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDetailTitleBrandTradeName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDetailBrandTradeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDetailBrandTradeName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDetailTitleVaccineLotNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDetailTitleVaccineLotNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDetailVaccineLotNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDetailVaccineLotNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDetailTitleExpiryD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDetailTitleExpiryD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDetailExpiryD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDetailExpiryD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trEffectiveFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trEffectiveFrom As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblDetailTitleEffectiveFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDetailTitleEffectiveFrom As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDetailEffectiveFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDetailEffectiveFrom As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trEffectiveTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trEffectiveTo As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblDetailTitleEffectiveTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDetailTitleEffectiveTo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDetailEffectiveTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDetailEffectiveTo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDetailUpToExpiryDtm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDetailUpToExpiryDtm As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gvSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvSummary As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblDetailTitleNewRecordStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDetailTitleNewRecordStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDetailNewRecordStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDetailNewRecordStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDetailTitleRequestType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDetailTitleRequestType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDetailRequestType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDetailRequestType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDetailTitleRequestedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDetailTitleRequestedBy As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDetailRequestedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDetailRequestedBy As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ibtnBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnBack As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibtnApproval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnApproval As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibtnReject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnReject As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''hfDetailTSMP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfDetailTSMP As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ViewMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewMsg As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''ibtnConfirmBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnConfirmBack As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibtnNoRecordBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnNoRecordBack As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ViewError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewError As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''ibtnReturn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnReturn As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ModalPopupConfirmApproval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModalPopupConfirmApproval As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''panPopupConfirmApproval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panPopupConfirmApproval As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ucNoticePopUpConfirmApproval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucNoticePopUpConfirmApproval As Global.HCVU.ucNoticePopUp

    '''<summary>
    '''ModalPopupConfirmReject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModalPopupConfirmReject As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''panPopupConfirmReject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panPopupConfirmReject As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ucNoticePopUpConfirmReject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucNoticePopUpConfirmReject As Global.HCVU.ucNoticePopUp
End Class
