'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class login1

    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''PageTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PageTitle As Global.System.Web.UI.HtmlControls.HtmlTitle

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''NonLoginPageKey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NonLoginPageKey As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''mvLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvLogin As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''vLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vLogin As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''lblBannerText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBannerText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkbtnTextOnlyVersion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnTextOnlyVersion As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lnkbtnTradChinese control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnTradChinese As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblCurrentLanguageTradChinese control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrentLanguageTradChinese As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkbtnEnglish control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnEnglish As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblCurrentLanguageEnglish control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrentLanguageEnglish As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''panSignin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panSignin As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblFunctionInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFunctionInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''udcTextOnlyMessageBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents udcTextOnlyMessageBox As Global.CustomControls.TextOnlyMessageBox

    '''<summary>
    '''lblRoleText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRoleText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnSignInSP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSignInSP As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblSignInSP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSignInSP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnSignInDataEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSignInDataEntry As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblSignInDataEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSignInDataEntry As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLoginAliasText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLoginAliasText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUserNameText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUserNameText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtUserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUserName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblUserNameAlert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUserNameAlert As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPasswordText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPasswordText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPassword As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPasswordAlert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPasswordAlert As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPinNoText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPinNoText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPinNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPinNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPinNoAlert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPinNoAlert As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSPIDText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSPIDText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSPID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSPID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSPIDAlert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSPIDAlert As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLogin As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hlContactUs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlContactUs As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''vConfirmDeclare control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vConfirmDeclare As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''tblBanner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblBanner As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''labelDescribeConcurrentAccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labelDescribeConcurrentAccess As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''labelExplainConcurrentAccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labelExplainConcurrentAccess As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''labelConfirmConcurrentAccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labelConfirmConcurrentAccess As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnConfirmReturn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfirmReturn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnConfirmLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfirmLogin As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''vNotification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vNotification As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''tblNotification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblNotification As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''lblNoticeHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoticeHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNoticeMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoticeMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trDeclaration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trDeclaration As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''chkDeclaration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDeclaration As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblDeclaration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDeclaration As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnNoticeOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNoticeOK As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnProceed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnProceed As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''vReminderObsoleteOS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vReminderObsoleteOS As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''tblReminderObsoleteOS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblReminderObsoleteOS As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''lblReminderObsoleteOSTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReminderObsoleteOSTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbtnReminderObsoleteOSFullVersion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnReminderObsoleteOSFullVersion As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbtnReminderObsoleteOSTradChinese control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnReminderObsoleteOSTradChinese As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblReminderTradChinese control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReminderTradChinese As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbtnReminderObsoleteOSEnglish control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnReminderObsoleteOSEnglish As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblReminderEnglish control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReminderEnglish As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReminderObsoleteOSHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReminderObsoleteOSHeading As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReminderObsoleteOSContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReminderObsoleteOSContent As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnReminderObsoleteOSOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReminderObsoleteOSOK As Global.System.Web.UI.WebControls.Button
End Class
