'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4971
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''udcScheme class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class udcScheme

    '''<summary>
    '''panScheme control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panScheme As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblScheme control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScheme As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlScheme control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlScheme As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''imgErrorScheme control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgErrorScheme As Global.System.Web.UI.WebControls.Image
End Class
