'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ucReadOnlyHCVSChina

    '''<summary>
    '''tblHCVSChina control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblHCVSChina As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''lblExchangeRateText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExchangeRateText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExchangeRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExchangeRate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRedeemAmountText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRedeemAmountText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRedeemAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRedeemAmount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trCoPaymentFee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trCoPaymentFee As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblCoPaymentFeeText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCoPaymentFeeText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCoPaymentFee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCoPaymentFee As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tr1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr1 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblPaymentTypeTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPaymentTypeTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPaymentType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPaymentType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReasonVisitText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReasonVisitText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReasonVisitToBeProvided control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReasonVisitToBeProvided As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divReasonForVisit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divReasonForVisit As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tblReasonForVisit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblReasonForVisit As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''trPrincipal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trPrincipal As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblPrimary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrimary As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReasonVisitL1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReasonVisitL1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trSecondary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trSecondary As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblSecondary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSecondary As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PlaceHolder1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PlaceHolder1 As Global.System.Web.UI.WebControls.PlaceHolder
End Class
