'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ucInputHKID

    '''<summary>
    '''panEnterDetailCreation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panEnterDetailCreation As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''panl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panl1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''hkid_cell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hkid_cell As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''lblCName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtENameSurname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtENameSurname As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblENameComma control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblENameComma As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtENameFirstrname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtENameFirstrname As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgENameError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgENameError As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''txtCCCode1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCCCode1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCCCode2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCCCode2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCCCode3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCCCode3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgCCCodeError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCCCodeError As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''btnSearchCCCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearchCCCode As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lblCCCTail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCCCTail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCCCode4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCCCode4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCCCode5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCCCode5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCCCode6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCCCode6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDOB As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rbGender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbGender As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''imgGenderError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgGenderError As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''txtHKIDIssueDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHKIDIssueDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgHKIDIssueDateError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgHKIDIssueDateError As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''txtHKID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHKID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''filtereditEnameSurname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtereditEnameSurname As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''filtereditEnameFirstname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtereditEnameFirstname As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''filtererditCCcode1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtererditCCcode1 As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''filtererditCCcode2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtererditCCcode2 As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''filtererditCCcode3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtererditCCcode3 As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''filtererditCCcode5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtererditCCcode5 As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''filtererditCCcode4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtererditCCcode4 As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''filtererditCCcode6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtererditCCcode6 As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''filtereditDOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtereditDOB As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''filtereditHKID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtereditHKID As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''filtereditHKIDIssueDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtereditHKIDIssueDate As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''panEnterDetailModify control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panEnterDetailModify As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''trReferenceNoModification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trReferenceNoModification As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblReferenceNoModificationText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReferenceNoModificationText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReferenceNoModification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReferenceNoModification As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHKICNoModificationText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHKICNoModificationText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHKICNoModification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHKICNoModification As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtHKICNoModification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHKICNoModification As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgHKICNoModificationError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgHKICNoModificationError As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblDOBModificationText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDOBModificationText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDOBModification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDOBModification As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgDOBModificationError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgDOBModificationError As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblENameModificationText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblENameModificationText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtENameSurnameModification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtENameSurnameModification As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblENameCommaModification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblENameCommaModification As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtENameFirstnameModification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtENameFirstnameModification As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgENameModificationError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgENameModificationError As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblENameSurnameModification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblENameSurnameModification As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblENameFirstnameModification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblENameFirstnameModification As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCCCodeModificationText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCCCodeModificationText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCCCode1Modification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCCCode1Modification As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCCCode2Modification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCCCode2Modification As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCCCode3Modification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCCCode3Modification As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCCCode4Modification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCCCode4Modification As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCCCode5Modification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCCCode5Modification As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCCCode6Modification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCCCode6Modification As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgCCCodeModificationError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCCCodeModificationError As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''btnSearchCCCodeModification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearchCCCodeModification As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lblCNameModificationText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCNameModificationText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCNameModification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCNameModification As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rbGenderModification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbGenderModification As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''trGenderImageInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trGenderImageInput As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblGenderModificationText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGenderModificationText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divGender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divGender As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tblIGender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblIGender As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''divFemale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divFemale As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''imgFemale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgFemale As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblIFemale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIFemale As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblIFemaleChi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIFemaleChi As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divMale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divMale As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''imgMale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgMale As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblIMale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIMale As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblIMaleChi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIMaleChi As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReadonlyGender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReadonlyGender As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgGenderModificationError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgGenderModificationError As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblDOIModificationText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDOIModificationText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDOIModification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDOIModification As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgDOIModificationError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgDOIModificationError As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''trTransactionNoModification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trTransactionNoModification As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblTransactionNoModificationText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTransactionNoModificationText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTransactionNoModification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTransactionNoModification As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''filtereditEnameSurnameModification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtereditEnameSurnameModification As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''filtereditEnameFirstnameModification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtereditEnameFirstnameModification As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''filtererditCCcode1Modification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtererditCCcode1Modification As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''filtererditCCcode2Modification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtererditCCcode2Modification As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''filtererditCCcode3Modification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtererditCCcode3Modification As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''filtererditCCcode4Modification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtererditCCcode4Modification As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''filtererditCCcode5Modification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtererditCCcode5Modification As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''filtererditCCcode6Modification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtererditCCcode6Modification As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''filtereditDOBModification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtereditDOBModification As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''filtereditDOIModification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtereditDOIModification As Global.AjaxControlToolkit.FilteredTextBoxExtender
End Class
