'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''ucInputAdoption class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class ucInputAdoption

    '''<summary>
    '''pnlModify control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlModify As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblOriginalRecordText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOriginalRecordText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAmendingRecordText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAmendingRecordText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDocumentTypeOriginalText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDocumentTypeOriginalText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDocumentTypeOriginal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDocumentTypeOriginal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNoOfEntryOriginalText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoOfEntryOriginalText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNoOfEntryOriginal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoOfEntryOriginal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPerfixNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPerfixNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblEntryNoSymbol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntryNoSymbol As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntryNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntryNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgEntryNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgEntryNo As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblNameOrignialText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNameOrignialText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNameOrignial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNameOrignial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtENameSurname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtENameSurname As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblENameComma control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblENameComma As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtENameFirstname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtENameFirstname As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgEName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgEName As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblGenderOriginalText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGenderOriginalText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblGenderOriginal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGenderOriginal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rbGender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbGender As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''imgGender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgGender As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblDOBOriginalText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDOBOriginalText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDOBOriginal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDOBOriginal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rbDOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbDOB As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtDOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDOB As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgDOBError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgDOBError As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''rbDOBInWord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbDOBInWord As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''ddlDOBinWordType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDOBinWordType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtDOBInWord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDOBInWord As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgDOBInWordError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgDOBInWordError As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''filtereditEntryNo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtereditEntryNo1 As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''filtereditEnameSurname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtereditEnameSurname As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''filtereditEnameFirstname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtereditEnameFirstname As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''filtereditDOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtereditDOB As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''filtereditDOBInWord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtereditDOBInWord As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''pnlNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlNew As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblNewNoOfEntryText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNewNoOfEntryText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNewPrefix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewPrefix As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblNewSymbol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNewSymbol As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNewNoOfEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewNoOfEntry As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblEntryNo_ModifyOneSide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntryNo_ModifyOneSide As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgNewNoOfEntryErr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgNewNoOfEntryErr As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblNewNameText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNewNameText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNewSurname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewSurname As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblNewEnameComma control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNewEnameComma As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNewGivenName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewGivenName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgNewENameErr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgNewENameErr As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblNewENameSurnameTips control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNewENameSurnameTips As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNewENameGivenNameTips control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNewENameGivenNameTips As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNewGenderText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNewGenderText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rboNewGender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rboNewGender As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''imgNewGenderErr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgNewGenderErr As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblNewDOBText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNewDOBText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rboNewDOBType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rboNewDOBType As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtNewDOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewDOB As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgNewDOBErr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgNewDOBErr As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''rboNewDOBInWord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rboNewDOBInWord As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''ddlNewDOBInWord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlNewDOBInWord As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtNewDOBInWord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewDOBInWord As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgNewDOBInWordErr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgNewDOBInWordErr As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''FilteredNewPerfixNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FilteredNewPerfixNo As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''FilteredNewNoOfEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FilteredNewNoOfEntry As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''FilteredNewENameSurname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FilteredNewENameSurname As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''FilteredNewENameGivenname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FilteredNewENameGivenname As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''FilteredNewDOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FilteredNewDOB As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''FilteredNewDOBInWord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FilteredNewDOBInWord As Global.AjaxControlToolkit.FilteredTextBoxExtender
End Class
