'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CallEHR

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''lbtnCallEHS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnCallEHS As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblCallEHR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCallEHR As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblVerifySystem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVerifySystem As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbtnVerifySystem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnVerifySystem As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblGetEhrWebS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGetEhrWebS As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbtnGetEhrWebS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnGetEhrWebS As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''mvFunction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvFunction As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''vVerifySystem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vVerifySystem As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''rblVMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblVMode As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''txtVEndpointURL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVEndpointURL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlVLoadSample control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlVLoadSample As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblVLoadSampleInstruction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVLoadSampleInstruction As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtVRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVRequest As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnVSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnVSubmit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cboVRemoveWhiteSpace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboVRemoveWhiteSpace As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''rblVSubmitOption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblVSubmitOption As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''txtVResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVResult As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''vGetEhrWebS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vGetEhrWebS As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''rblGMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblGMode As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''txtGEndPointURL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGEndPointURL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlGLoadSample control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlGLoadSample As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblGLoadSampleInstruction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGLoadSampleInstruction As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtGRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGRequest As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnGSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGSubmit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cboGRemoveWhiteSpace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboGRemoveWhiteSpace As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''rblGSubmitOption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblGSubmitOption As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''txtGResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGResult As Global.System.Web.UI.WebControls.TextBox
End Class
