'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ucInputVSSCOVID19

    '''<summary>
    '''panBooth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panBooth As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblCBoothText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCBoothText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlCBooth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCBooth As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''imgCBoothError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCBoothError As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''panCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panCategory As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblCCategoryText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCCategoryText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlCCategoryCovid19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCCategoryCovid19 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCCategory As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgCCategoryError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCCategoryError As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblCMainCategoryText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCMainCategoryText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgCCategoryInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCCategoryInfo As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ddlCMainCategoryCovid19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCMainCategoryCovid19 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCMainCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCMainCategory As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgCMainCategoryError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCMainCategoryError As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblCSubCategoryText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCSubCategoryText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlCSubCategoryCovid19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCSubCategoryCovid19 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCSubCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCSubCategory As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgCSubCategoryError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCSubCategoryError As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblCVaccineBrandText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCVaccineBrandText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlCVaccineBrandCovid19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCVaccineBrandCovid19 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCVaccineBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCVaccineBrand As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgCVaccineBrandError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCVaccineBrandError As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblCVaccineLotNoText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCVaccineLotNoText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlCVaccineLotNoCovid19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCVaccineLotNoCovid19 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCVaccineLotNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCVaccineLotNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgCVaccineLotNoError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCVaccineLotNoError As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''panVaccineName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panVaccineName As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblCVaccineText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCVaccineText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCVaccine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCVaccine As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCDoseText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCDoseText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlCDoseCovid19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCDoseCovid19 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''imgCDoseError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCDoseError As Global.System.Web.UI.WebControls.Image
End Class
