'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SchoolListSearch

    '''<summary>
    '''udcMsgBoxInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents udcMsgBoxInfo As Global.CustomControls.InfoMessageBox

    '''<summary>
    '''lblSchoolListFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSchoolListFilter As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSchoolListFilterCriteria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSchoolListFilterCriteria As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ibtnSchoolListFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnSchoolListFilter As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''gvSelectedSchoolRecord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvSelectedSchoolRecord As Global.System.Web.UI.WebControls.GridView
End Class
