'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TestPCDWS

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''lblSys_CodeText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSys_CodeText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSys_Code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSys_Code As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblEnrolment_Ref_NoText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEnrolment_Ref_NoText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtEnrolment_Ref_No control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEnrolment_Ref_No As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblLoginText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLoginText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLogin As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnGetLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGetLogin As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblPwdText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPwdText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPwd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnGetPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGetPassword As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblURItext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblURItext As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtURI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtURI As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnGetURI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGetURI As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnGetTesterURI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGetTesterURI As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblProxyChoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProxyChoice As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rdolstProxyChoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdolstProxyChoice As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblSPID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSPID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSPID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSPID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPlatFormCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPlatFormCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rdolstPlatformCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdolstPlatformCode As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''txtPlatFormCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPlatFormCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTypeOfPractice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTypeOfPractice As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTypeOfPracticeHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTypeOfPracticeHelp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rdolstTypeOfPractice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdolstTypeOfPractice As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblGenRequestXML control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGenRequestXML As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rdolstGenRequestXML control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdolstGenRequestXML As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblActions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblActions As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnGenerateRequestXML control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGenerateRequestXML As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblArrows control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblArrows As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnSubmitXML control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitXML As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblBeginTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBeginTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEndTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEndTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDuration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDuration As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDebugMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDebugMsg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtM_DebugMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtM_DebugMsg As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblRequestXML control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRequestXML As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnRequest_FormatXML control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRequest_FormatXML As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtM_RequestXML control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtM_RequestXML As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblResultXML control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblResultXML As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnResult_FormatXML control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnResult_FormatXML As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnResult_Clear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnResult_Clear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtM_ResultXML control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtM_ResultXML As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSubmitXML control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubmitXML As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnUploadEnrolInfoRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUploadEnrolInfoRequest As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCreatePCDSPAcct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreatePCDSPAcct As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnTransferPracticeInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTransferPracticeInfo As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCheckIsActiveSP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCheckIsActiveSP As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdnMessageID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnMessageID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnSelectedXMLFcn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnSelectedXMLFcn As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnSelectedTypeOfPractice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnSelectedTypeOfPractice As Global.System.Web.UI.WebControls.HiddenField
End Class
