'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:2.0.50727.1433
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by wsdl, Version=2.0.50727.42.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Web.Services.WebServiceBindingAttribute(Name:="NotificationSenderBinding", [Namespace]:="http://spica-scopes.hksarg/spica/NotificationSender.xsd1")>  _
Partial Public Class NotificationSender
    Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
    
    Private CallNotificationSenderOperationCompleted As System.Threading.SendOrPostCallback
    
    '''<remarks/>
    Public Sub New()
        MyBase.New
        Me.Url = "https://EGIS/spica/services/NotificationSenderService"
    End Sub
    
    '''<remarks/>
    Public Event CallNotificationSenderCompleted As CallNotificationSenderCompletedEventHandler
    
    '''<remarks/>
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("NotificationSender", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
    Public Function CallNotificationSender(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://spica-scopes.hksarg/spica/NotificationSender.xsd1")> ByVal NotificationSenderRequest As NotificationSenderRequest) As <System.Xml.Serialization.XmlElementAttribute("NotificationSenderResponse", [Namespace]:="http://spica-scopes.hksarg/spica/NotificationSender.xsd1")> NotificationSenderResponse
        Dim results() As Object = Me.Invoke("CallNotificationSender", New Object() {NotificationSenderRequest})
        Return CType(results(0),NotificationSenderResponse)
    End Function
    
    '''<remarks/>
    Public Function BeginCallNotificationSender(ByVal NotificationSenderRequest As NotificationSenderRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("CallNotificationSender", New Object() {NotificationSenderRequest}, callback, asyncState)
    End Function
    
    '''<remarks/>
    Public Function EndCallNotificationSender(ByVal asyncResult As System.IAsyncResult) As NotificationSenderResponse
        Dim results() As Object = Me.EndInvoke(asyncResult)
        Return CType(results(0),NotificationSenderResponse)
    End Function
    
    '''<remarks/>
    Public Overloads Sub CallNotificationSenderAsync(ByVal NotificationSenderRequest As NotificationSenderRequest)
        Me.CallNotificationSenderAsync(NotificationSenderRequest, Nothing)
    End Sub
    
    '''<remarks/>
    Public Overloads Sub CallNotificationSenderAsync(ByVal NotificationSenderRequest As NotificationSenderRequest, ByVal userState As Object)
        If (Me.CallNotificationSenderOperationCompleted Is Nothing) Then
            Me.CallNotificationSenderOperationCompleted = AddressOf Me.OnCallNotificationSenderOperationCompleted
        End If
        Me.InvokeAsync("CallNotificationSender", New Object() {NotificationSenderRequest}, Me.CallNotificationSenderOperationCompleted, userState)
    End Sub
    
    Private Sub OnCallNotificationSenderOperationCompleted(ByVal arg As Object)
        If (Not (Me.CallNotificationSenderCompletedEvent) Is Nothing) Then
            Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
            RaiseEvent CallNotificationSenderCompleted(Me, New CallNotificationSenderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
        End If
    End Sub
    
    '''<remarks/>
    Public Shadows Sub CancelAsync(ByVal userState As Object)
        MyBase.CancelAsync(userState)
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://spica-scopes.hksarg/spica/NotificationSender.xsd1")>  _
Partial Public Class NotificationSenderRequest
    
    Private chanTypeField As String
    
    Private contentDetailField As Content
    
    Private recipientDetailField() As Recipient
    
    '''<remarks/>
    Public Property ChanType() As String
        Get
            Return Me.chanTypeField
        End Get
        Set
            Me.chanTypeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property ContentDetail() As Content
        Get
            Return Me.contentDetailField
        End Get
        Set
            Me.contentDetailField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("RecipientDetail")>  _
    Public Property RecipientDetail() As Recipient()
        Get
            Return Me.recipientDetailField
        End Get
        Set
            Me.recipientDetailField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://spica-scopes.hksarg/spica/NotificationSender.xsd1")>  _
Partial Public Class Content
    
    Private charSetField As String
    
    Private contentTypeField As String
    
    Private subjectField As String
    
    Private content1Field As String
    
    Private atthFileField() As Attachment
    
    '''<remarks/>
    Public Property CharSet() As String
        Get
            Return Me.charSetField
        End Get
        Set
            Me.charSetField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property ContentType() As String
        Get
            Return Me.contentTypeField
        End Get
        Set
            Me.contentTypeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Subject() As String
        Get
            Return Me.subjectField
        End Get
        Set
            Me.subjectField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Content")>  _
    Public Property Content1() As String
        Get
            Return Me.content1Field
        End Get
        Set
            Me.content1Field = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("AtthFile")>  _
    Public Property AtthFile() As Attachment()
        Get
            Return Me.atthFileField
        End Get
        Set
            Me.atthFileField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://spica-scopes.hksarg/spica/NotificationSender.xsd1")>  _
Partial Public Class Attachment
    
    Private contentTypeField As String
    
    Private fileNameField As String
    
    Private fileContentField() As Byte
    
    '''<remarks/>
    Public Property ContentType() As String
        Get
            Return Me.contentTypeField
        End Get
        Set
            Me.contentTypeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property FileName() As String
        Get
            Return Me.fileNameField
        End Get
        Set
            Me.fileNameField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
    Public Property FileContent() As Byte()
        Get
            Return Me.fileContentField
        End Get
        Set
            Me.fileContentField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://spica-scopes.hksarg/spica/NotificationSender.xsd1")>  _
Partial Public Class NotiStatus
    
    Private chanAddrField As String
    
    Private resultCdField As String
    
    Private resultMesgField As String
    
    '''<remarks/>
    Public Property ChanAddr() As String
        Get
            Return Me.chanAddrField
        End Get
        Set
            Me.chanAddrField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property ResultCd() As String
        Get
            Return Me.resultCdField
        End Get
        Set
            Me.resultCdField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property ResultMesg() As String
        Get
            Return Me.resultMesgField
        End Get
        Set
            Me.resultMesgField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://spica-scopes.hksarg/spica/NotificationSender.xsd1")>  _
Partial Public Class Recipient
    
    Private chanAddrField As String
    
    Private recipientAtthFileField() As Attachment
    
    '''<remarks/>
    Public Property ChanAddr() As String
        Get
            Return Me.chanAddrField
        End Get
        Set
            Me.chanAddrField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("RecipientAtthFile")>  _
    Public Property RecipientAtthFile() As Attachment()
        Get
            Return Me.recipientAtthFileField
        End Get
        Set
            Me.recipientAtthFileField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://spica-scopes.hksarg/spica/NotificationSender.xsd1")>  _
Partial Public Class NotificationSenderResponse
    
    Private statusField As String
    
    Private notificationStatusField() As NotiStatus
    
    '''<remarks/>
    Public Property Status() As String
        Get
            Return Me.statusField
        End Get
        Set
            Me.statusField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("NotificationStatus")>  _
    Public Property NotificationStatus() As NotiStatus()
        Get
            Return Me.notificationStatusField
        End Get
        Set
            Me.notificationStatusField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")>  _
Public Delegate Sub CallNotificationSenderCompletedEventHandler(ByVal sender As Object, ByVal e As CallNotificationSenderCompletedEventArgs)

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code")>  _
Partial Public Class CallNotificationSenderCompletedEventArgs
    Inherits System.ComponentModel.AsyncCompletedEventArgs
    
    Private results() As Object
    
    Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
        MyBase.New(exception, cancelled, userState)
        Me.results = results
    End Sub
    
    '''<remarks/>
    Public ReadOnly Property Result() As NotificationSenderResponse
        Get
            Me.RaiseExceptionIfNecessary
            Return CType(Me.results(0),NotificationSenderResponse)
        End Get
    End Property
End Class
