'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class eHealthAccountDeathRecordFileConfirmation

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''imgHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgHeader As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''udcInfoMessageBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents udcInfoMessageBox As Global.CustomControls.InfoMessageBox

    '''<summary>
    '''udcMessageBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents udcMessageBox As Global.CustomControls.MessageBox

    '''<summary>
    '''mvCore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvCore As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''vGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vGrid As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''cboShowPendingConfirmationOnly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboShowPendingConfirmationOnly As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''gvDeathRecordFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvDeathRecordFile As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''mvOuterButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvOuterButton As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''ViewNoSelectFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewNoSelectFile As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''ViewSelectFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewSelectFile As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''ibtnViewDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnViewDetail As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibtnConfirmFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnConfirmFile As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibtnRemoveFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnRemoveFile As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lblGNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGNote As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''vFinish control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vFinish As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''ibtnFReturn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnFReturn As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnHiddenViewDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHiddenViewDetail As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''popupViewDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupViewDetail As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''panViewDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panViewDetail As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''panViewDetailHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panViewDetailHeading As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblViewDetailHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblViewDetailHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''udcVDInfoMessageBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents udcVDInfoMessageBox As Global.CustomControls.InfoMessageBox

    '''<summary>
    '''lblSVDDeathRecordFileIDText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSVDDeathRecordFileIDText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblVDDeathRecordFileID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVDDeathRecordFileID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblVDDeathRecordFileIDFail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVDDeathRecordFileIDFail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblVDTotalNoOfRecordText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVDTotalNoOfRecordText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblVDTotalNoOfRecord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVDTotalNoOfRecord As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblVDNoOfRecordWithHKIDText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVDNoOfRecordWithHKIDText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblVDNoOfFailRecordText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVDNoOfFailRecordText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblVDNoOfRecordWithHKID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVDNoOfRecordWithHKID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblVDNoOfFailRecord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVDNoOfFailRecord As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblVDNoOfRecordWithoutHKIDText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVDNoOfRecordWithoutHKIDText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblVDShowFailRecordOnlyText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVDShowFailRecordOnlyText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblVDNoOfRecordWithoutHKID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVDNoOfRecordWithoutHKID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboVDShowFailRecordOnly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboVDShowFailRecordOnly As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblVDShowRecordWithRowNoInText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVDShowRecordWithRowNoInText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlVDShowRecordWithRowNoIn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlVDShowRecordWithRowNoIn As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboVDMaskDocumentNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboVDMaskDocumentNo As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''hfVDMaskDocumentNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfVDMaskDocumentNo As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''panVDEntryStaging control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panVDEntryStaging As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''gvVDEntryStaging control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvVDEntryStaging As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''ibtnVDClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnVDClose As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibtnPopupConfirmFileConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnPopupConfirmFileConfirm As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibtnPopupConfirmFileCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnPopupConfirmFileCancel As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnHiddenRemoveFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHiddenRemoveFile As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''popupRemoveFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupRemoveFile As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''panRemoveFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panRemoveFile As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''panRemoveFileHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panRemoveFileHeading As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblRemoveFileHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRemoveFileHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgPopupRemoveFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgPopupRemoveFile As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblPopupRemoveFileText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPopupRemoveFileText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ibtnPopupRemoveFileConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnPopupRemoveFileConfirm As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibtnPopupRemoveFileCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnPopupRemoveFileCancel As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnHiddenUnmask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHiddenUnmask As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''popupUnmask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupUnmask As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''panUnmask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panUnmask As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''udcPUInputToken control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents udcPUInputToken As Global.HCVU.ucInputToken
End Class
