'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''reportCriteriaPeriodFromToDateTime class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class reportCriteriaPeriodFromToDateTime
    
    '''<summary>
    '''lblInput01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInput01 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtPeriodFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPeriodFrom As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''filterPeriodFromDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filterPeriodFromDate As Global.AjaxControlToolkit.FilteredTextBoxExtender
    
    '''<summary>
    '''btnFromDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFromDate As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''calExFromDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calExFromDate As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''txtFromTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFromTime As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''maskedFromTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents maskedFromTime As Global.AjaxControlToolkit.MaskedEditExtender
    
    '''<summary>
    '''imgPeriodFromError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgPeriodFromError As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''lblInput02 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInput02 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtPeriodTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPeriodTo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''filterPeriodToDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filterPeriodToDate As Global.AjaxControlToolkit.FilteredTextBoxExtender
    
    '''<summary>
    '''btnToDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnToDate As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''calExToDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calExToDate As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''txtToTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtToTime As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''maskedToTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents maskedToTime As Global.AjaxControlToolkit.MaskedEditExtender
    
    '''<summary>
    '''imgPeriodToError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgPeriodToError As Global.System.Web.UI.WebControls.Image
End Class
