'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ucVaccinationRecord

    '''<summary>
    '''udcMessageBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents udcMessageBox As Global.CustomControls.MessageBox

    '''<summary>
    '''udcInfoMessageBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents udcInfoMessageBox As Global.CustomControls.InfoMessageBox

    '''<summary>
    '''lblAccountInformation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccountInformation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mvDocumentType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvDocumentType As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''ViewControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewControl As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''udcReadOnlyDocumnetType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents udcReadOnlyDocumnetType As Global.HCSP.ucReadOnlyDocumnetType

    '''<summary>
    '''ViewSimple control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewSimple As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''lblSDocumentTypeText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSDocumentTypeText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSDocumentType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSDocumentType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSNameText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSNameText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSEName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSEName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSCName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSCName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSDOBGenderText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSDOBGenderText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSDOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSDOB As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSDOBGenderSlash control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSDOBGenderSlash As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSGender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSGender As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSDocumentNoText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSDocumentNoText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSDocumentNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSDocumentNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSECSerialNoText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSECSerialNoText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSECSerialNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSECSerialNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ViewSimpleNoName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewSimpleNoName As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''lblSNDocumentTypeText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSNDocumentTypeText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSNDocumentType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSNDocumentType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSNDocumentNoText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSNDocumentNoText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSNDocumentNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSNDocumentNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSNDOBText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSNDOBText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSNDOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSNDOB As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblVaccinationRecord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVaccinationRecord As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNoOfRecord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoOfRecord As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEHSText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEHSText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEHS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEHS As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''panHA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panHA As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblHAText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHAText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHA As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hfHA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfHA As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''panDH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panDH As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblDHText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDHText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDH As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hfDH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfDH As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lblNoVaccinationRecord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoVaccinationRecord As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gvVaccinationRecord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvVaccinationRecord As Global.System.Web.UI.WebControls.GridView
End Class
